import { Inter, Vazirmatn } from "next/font/google";
import { ReactNode } from "react";
import "./globals.css";

const vazirMatn = Vazirmatn({ subsets: ["arabic"] });
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children : ReactNode }) {
	return (
		<html
			lang="en"
			className={`${vazirMatn.className} text-white h-full antialiased`}
		>
			<body className="min-h-full flex flex-col">{children}</body>
		</html>
	);
}
